  - name: Install needed packages
    ansible.builtin.shell:
      cmd: |
        sudo apt-get install -y apt-transport-https ca-certificates curl gpg
  
  - name: Add kubernetes to packages manager
    ansible.builtin.shell:
      cmd: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update

  - name: Install kubelet, kubeadm and kubectl
    ansible.builtin.shell:
      cmd: |
        sudo apt-get install -y kubelet kubeadm kubectl docker.io
        sudo apt-mark hold kubelet kubeadm kubectl
        sudo systemctl enable --now kubelet