apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: web-http-visibility
  namespace: hubble-demo
spec:
  endpointSelector:
    matchLabels:
      app: web
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: client
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: "/.*"
