apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: web-deny-observer
spec:
  endpointSelector:
    matchLabels:
      app: web
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: not-observer

