apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: grpc-example
spec:
  parentRefs:
    - name: cilium-gw
  rules:
    - matches:
        - method:
            service: demo.EchoService
      backendRefs:
        - name: grpc-echo
          port: 50051

