apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-wordpress
spec:
  interval: 1h
  timeout: 5m
  releaseName: flux-wordpress
  targetNamespace: flux-helm-test
  chart:
    spec:
      chart: wordpress
      version: '24.1.18'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1m

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3