apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: haproxytech
  namespace: flux-system
spec:
  interval: 1h
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-haproxy
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  releaseName: flux-haproxy
  targetNamespace: flux-helm-test
  chart:
    spec:
      chart: haproxy
      version: '1.24.0'
      sourceRef:
        kind: HelmRepository
        name: haproxytech
      interval: 1m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3