apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: hubble-demo
  labels:
    app: client
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:8.11.1
      command:
        - sleep
        - 1d
