- name: Add defualt mosquitto file
  ansible.builtin.shell:
    cmd: |
      echo "listener 1883 0.0.0.0
      allow_anonymous false
      password_file /etc/mosquitto/passwd" > /etc/mosquitto/conf.d/default.conf

- name: Clean mosquitto password file
  ansible.builtin.shell:
    cmd: |
      rm -rf /etc/mosquitto/passwd
      touch /etc/mosquitto/passwd

- name: add user and password to mosquitto password file
  ansible.builtin.shell:
    cmd: |
      echo "{{item.username}}:{{item.password}}" >> /etc/mosquitto/passwd
  loop: "{{ mosquitto_users }}"

- name: Hash mosquitto password
  ansible.builtin.shell:
    cmd: |
      mosquitto_passwd -U /etc/mosquitto/passwd

