apiVersion: 1

deleteDatasources:
  - name: Pyroscope
    orgId: 1

datasources:
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    uid: pyroscope_datasource
    url: http://pyroscope:4040
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      minStep: "15s"
