apiVersion: v1
kind: Namespace
metadata:
  name: bgp-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: bgp-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: bgp-lab
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
