apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-good-client-to-web
spec:
  endpointSelector:
    matchLabels:
      app: web
  ingress:
    - fromEndpoints:
        - matchLabels:
            role: allowed
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
