apiVersion: v1
kind: Secret
metadata:
  name: minio-artifacts
  namespace: argo
type: Opaque
stringData:
  accesskey: app-user
  secretkey: app-user-secret-123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    artifactRepository:
      archiveLogs: true
      s3:
        bucket: argo-artifacts
        endpoint: argo-artifacts.minio.svc.cluster.local:9000
        insecure: true
        accessKeySecret:
          name: minio-artifacts
          key: accesskey
        secretKeySecret:
          name: minio-artifacts
          key: secretkey