apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: client-to-server-http
spec:
  endpointSelector:
    matchLabels:
      role: client
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: l3-lab
            role: server
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
