apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        node-lab: target
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: access-allowed
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelector:
    node-lab: allowed
  restartPolicy: Never
  containers:
    - name: access-allowed
      image: curlimages/curl:8.10.1
      command:
        - sleep
        - "3600"
---
apiVersion: v1
kind: Pod
metadata:
  name: access-deny
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelector:
    node-lab: denied
  restartPolicy: Never
  containers:
    - name: access-deny
      image: curlimages/curl:8.10.1
      command:
        - sleep
        - "3600"
